# When manually running the pipeline, you can select whether it
# succeeds or fails.

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'

stages:
- stage: QA
  displayName: Build QA stage
  jobs:
  - job: Work
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET core SDK'
      inputs:
        version: 6.x
        performMultiLevelLookup: true
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'
      
  # This job creates a work item, and only runs if the previous job failed
  - job: ErrorHandler
    strategy:
        matrix:
          linux:
            imageName: "ubuntu-latest"
        maxParallel: 1
    dependsOn: Work
    condition: failed()
    steps: 
    - bash: |
        az boards work-item create \
          --title "Build $(build.buildNumber) failed" \
          --type Bug \
          --org $(System.TeamFoundationCollectionUri) \
          --project $(System.TeamProject)
      env: 
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      displayName: 'Create work item on failure'
